#tomcat配置
server:
  port: 8080
#  port: 443
  #项目出错时跳转到的页面
  error:
    path: error
  tomcat:
    #tomcate编码
    uri-encoding: UTF-8
    threads:
      max: 600
    #存放tomcat运行日志和临时文件目录
    basedir: temp
  # session失效时间
  servlet:
    session:
      timeout: 199m
    #配置一下响应编码,防止FastJson乱码
    encoding:
      force-response: true






##HTTPS证书配置
#  ssl:
#    #key-store表示密钥文件名
#    key-store: classpath:https/sang.p12
#    #key-alias表示密钥别名
#    key-alias: tomcathttps
#    #在cmd命令执行过程中输入的密码:密钥库口令
#    key-store-password: xbcroot


spring:
  #配置数据源
  datasource:
    one:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql:///studentscore
      username: root
      password: root
    two:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql:///vueblog
      username: root
      password: root

  #jpa配置
  jpa:
    #是否在控制台打印JPA执行过程生成的SQL
    show-sql: true
    #对应的数据库是MySQL
    database: mysql
    #在项目启动时根据实体类更新数据库中的表
    hibernate:
      ddl-auto: update


  #thymeleaf配置
  thymeleaf:
    #是否开启缓存,开发时设置为fase,默认true
    cache: false
    # 检查模板是否存在,默认是true
    check-template: true
    #检查模板位置是否存在,默认true
    check-template-location: true
    #模板编码
    encoding: UTF-8
    #模板位置
    prefix: classpath:/templates/
    #模板文件后缀
    suffix: .html
    #content-type配置
    servlet:
      content-type: text/html

#  #freemarker配置
#  freemarker:
#    #HttpServletRequest的属性是否可以覆盖controller中的model的同名项
#    allow-request-override: false
#    #HttpSession的属性是否可以覆盖controller中的model的同名项
#    allow-session-override: false
#    #是否开启缓存
#    cache: false
#    #模板编码
#    charset: UTF-8
#    #content-type值
#    content-type: text/html
#    #是否检查模板位置
#    check-template-location: true
#    #是否将HttpServletRequest的属性添加到Model中
#    expose-request-attributes: false
#    #是否将HttpSession的属性添加到Model中
#    expose-session-attributes: false
#    suffix: .ftl
#    template-loader-path: classpath:/templates/

  #静态资源过滤策略
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/

  #文件上传设置
  servlet:
    multipart:
      #是否开启文件上传支持，默认为true
      enabled: true
      #文件写入磁盘的阈值，默认为0
      file-size-threshold: 0
      #上传文件的临时保存位置
      location: E:\\temp
      #上传的单个文件的最大大小，默认为1MB
      max-file-size: 1MB
      #多文件上传时文件的总大小，默认为10MB
      max-request-size: 10MB
      #文件是否延迟解析，默认为false
      resolve-lazily: false








book:
  name: 西游记
  author: 吴承恩
#mybatis:
#  config-location: classpath:/mapper/*.xml
